# NumPy & Pandas in Python for Data Handling

Python lists are slow for numeric tasks

NumPy is fast for numerical data

Pandas is used for structured/tabular data

>pip install numpy pandas

# Numpy

NumPy ek Python library hai jo fast numerical calculations ke liye use hoti hai.

Isme arrays hote hain jo list se zyada efficient aur powerful hote hain.

Large datasets ke saath kaam karna easy ho jata hai iske functions ki wajah se.

Mathematical operations like addition, multiplication bahut fast hoti hain.

Scientific computing ke liye ye backbone jaisi hai Python mein.

In [1]:
import numpy as np

# Creating 1D array
arr = np.array([1, 2, 3])
print(arr)

# Creating 2D array
matrix = np.array([[1, 2], [3, 4]])
print(matrix)

# Data types and shape
print(arr.dtype)
print(matrix.shape)

[1 2 3]
[[1 2]
 [3 4]]
int32
(2, 2)


In [2]:
arr = np.array([10, 20, 30])

# Scalar operations
print(arr + 5)
print(arr * 2)

# Vectorized operations
arr2 = np.array([1, 2, 3])
print(arr + arr2)

# Logical operations
print(arr > 15)


[15 25 35]
[20 40 60]
[11 22 33]
[False  True  True]


In [3]:
arr = np.array([1, 2, 3, 4, 5])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

15
3.0
5
1
1.4142135623730951


In [4]:
# Reshape
a = np.arange(12)
a = a.reshape((3, 4))
print(a)

# Random numbers
print(np.random.rand(3))
print(np.random.randint(1, 10, size=(2, 3)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0.30788382 0.11705226 0.45309159]
[[6 6 4]
 [8 7 9]]


# Pandas

Pandas ek data manipulation aur analysis library hai Python ke liye.

Ye tabular data ko handle karta hai DataFrames ke through—Excel jaise.

Missing data, filtering, grouping—sab kuch easily manage hota hai.

CSV, Excel, SQL jaise sources se data import/export karna simple hai.

Data science projects mein Pandas ek must-have tool hai.

In [5]:
import pandas as pd

data = [10, 20, 30]
s = pd.Series(data, index=['a', 'b', 'c'])
print(s)

# Accessing
print(s['b'])

a    10
b    20
c    30
dtype: int64
20


In [61]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [24, 25, 23],
    'Marks': [87, 91, 78]
}

df = pd.DataFrame(data)
df

Name  Age  Marks
0    Alice   24     87
1      Bob   25     91
2  Charlie   23     78

In [7]:
print(df.describe())
print(df.info())
print(df.head())
print(df.tail())

# Add column
df['Grade'] = ['A', 'A+', 'B']

        Age      Marks
count   3.0   3.000000
mean   24.0  85.333333
std     1.0   6.658328
min    23.0  78.000000
25%    23.5  82.500000
50%    24.0  87.000000
75%    24.5  89.000000
max    25.0  91.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   Marks   3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None
      Name  Age  Marks
0    Alice   24     87
1      Bob   25     91
2  Charlie   23     78
      Name  Age  Marks
0    Alice   24     87
1      Bob   25     91
2  Charlie   23     78


In [8]:
# Missing values
df['Marks'] = [90, None, 80]
print(df.isnull())

# Fill NA
df.fillna(0, inplace=True)


    Name    Age  Marks  Grade
0  False  False  False  False
1  False  False   True  False
2  False  False  False  False


In [47]:
df = pd.read_csv("Data Sample Storage/customers-100.csv")
df.head(2)

Index      Customer Id First Name Last Name          Company  \
0      1  DD37Cf93aecA6Dc     Sheryl    Baxter  Rasmussen Group   
1      2  1Ef7b82A4CAAD10    Preston    Lozano      Vega-Gentry   

                City   Country       Phone 1           Phone 2  \
0       East Leonard     Chile  229.077.5154  397.884.0519x718   
1  East Jimmychester  Djibouti    5153435776  686-620-1820x944   

                      Email Subscription Date                     Website  
0  zunigavanessa@smith.info        2020-08-24  http://www.stephenson.com/  
1           vmata@colon.com        2021-04-23       http://www.hobbs.com/

In [48]:
# Filter students with marks > 80
df[df['Index'] > 8].head()

Index      Customer Id First Name  Last Name                     Company  \
8       9  C2dE4dEEc489ae0     Sheryl     Meyers              Browning-Simon   
9      10  8C2811a503C7c5a   Michelle  Gallagher                Beck-Hendrix   
10     11  216E205d6eBb815       Carl  Schroeder  Oconnell, Meza and Everett   
11     12  CEDec94deE6d69B      Jenna     Dodson   Hoffman, Reed and Mcclain   
12     13  e35426EbDEceaFF     Tracey       Mata              Graham-Francis   

                 City      Country            Phone 1                Phone 2  \
8        Robersonstad       Cyprus  854-138-4911x5772    +1-448-910-2276x729   
9          Elaineberg  Timor-Leste   739.218.2516x459   001-054-401-0347x617   
10       Shannonville     Guernsey   637-854-0256x825       114.336.0784x788   
11        East Andrea      Vietnam      (041)737-3846  +1-556-888-3485x42608   
12  South Joannamouth         Togo   001-949-844-8787          (855)713-8773   

                      Email Subscription Date                      Website  
8   mariokhan@ryan-pope.org        2020-01-13     https://www.bullock.net/  
9         mdyer@escobar.net        2021-11-08           https://arias.com/  
10       kirksalas@webb.com        2021-10-20  https://simmons-hurley.com/  
11       mark42@robbins.com        2020-11-29      http://www.douglas.net/  
12         alex56@walls.org        2021-12-02         http://www.beck.com/

In [49]:
df.tail()

Index      Customer Id First Name Last Name                Company  \
95     96  cb8E23e48d22Eae       Karl     Greer              Carey LLC   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson  Ware, Burns and Oneal   
97     98  28CDbC0dFe4b1Db       Fred    Guerra          Schmitt-Jones   
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer     Fitzgerald-Harrell   
99    100  2354a0E336A91A1   Clarence    Haynes     Le, Nash and Cross   

               City          Country               Phone 1  \
95     East Richard           Guyana   (188)169-1674x58692   
96     New Bradview        Sri Lanka       +1-846-706-2218   
97       Ortegaland  Solomon Islands  +1-753-067-8419x7170   
98  Lake Elijahview            Aruba         (530)311-9786   
99        Judymouth         Honduras         (753)813-6941   

                   Phone 2                           Email Subscription Date  \
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30   
96            605.413.3198               vkemp@ferrell.com        2021-07-10   
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18   
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11   
99            783.639.1472          colleen91@faulkner.biz        2020-03-11   

                              Website  
95            http://hayes-perez.com/  
96         https://novak-allison.com/  
97              https://www.ross.com/  
98               http://watkins.info/  
99  http://www.hatfield-saunders.net/

In [50]:
df.count()

Index                100
Customer Id          100
First Name           100
Last Name            100
Company              100
City                 100
Country              100
Phone 1              100
Phone 2              100
Email                100
Subscription Date    100
Website              100
dtype: int64

In [51]:
df.count().isnull()

Index                False
Customer Id          False
First Name           False
Last Name            False
Company              False
City                 False
Country              False
Phone 1              False
Phone 2              False
Email                False
Subscription Date    False
Website              False
dtype: bool

In [60]:
print(df["Country"])

0                          Chile
1                       Djibouti
2            Antigua and Barbuda
3             Dominican Republic
4     Slovakia (Slovak Republic)
                 ...            
95                        Guyana
96                     Sri Lanka
97               Solomon Islands
98                         Aruba
99                      Honduras
Name: Country, Length: 100, dtype: object



Question 1: NumPy Program**

**Q1:** Write a Python program using NumPy to:

* Create a 1D array of values `[5, 10, 15, 20]`
* Add `10` to each element
* Print the final array

**Expected Output:**

```
[15 20 25 30]
```

---

### ✅ **Question 2: Pandas Program**

**Q2:** Write a Python program using Pandas to:

* Create a DataFrame with columns: `Name`, `Age`, and `Marks`
* Add a new column called `Result` with values `['Pass', 'Pass', 'Fail']`
* Print the updated DataFrame

**Expected Output:**

```
     Name  Age  Marks Result
0   Alice   24     87   Pass
1     Bob   25     91   Pass
2  Charlie   23     78   Fail
```