# Numpy & Pandas

In [6]:
import numpy as np
# arr = np.array()
arr = np.array([1,2,3]) # 1D Array
arr.dtype

dtype('int32')

In [5]:
arr = np.array([[1,2,3],[4,5,6]]) # 2D Array
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr = np.array([[1,2,3],[4,5,6]]) # 2D Array
print(arr)
arr.shape

[[1 2 3]
 [4 5 6]]


(2, 3)

In [18]:
arr1 = np.array([1,2,3]) # 1D Array
print(arr1 *3,"multiple")
print(arr1 +3,"addition")

[3 6 9] multiple
[4 5 6] addition


In [23]:
# Vectorized operation
arr1 = np.array([1,6,3]) # 1D Array
arr2 = np.array([9,5,6])

In [20]:
print(arr1 + arr2)

[10  7  9]


In [21]:
print(arr1 * arr2)

[ 9 10 18]


In [25]:
# Logical operation
print(arr1>arr2)

[False  True False]


In [26]:
arr1 = np.array([1,6,3,23,454,454,576,787]) # 1D Array
print(np.sum(arr1))

2304


In [27]:
print(np.mean(arr1))

288.0


In [28]:
print(np.max(arr1))

787


In [29]:
print(np.min(arr1))

1


In [30]:
print(np.std(arr1))

295.8884925102698


In [50]:
a = np.arange(16)
a = a.reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [37]:
print(np.random.rand(3))

[0.22192089 0.21268438 0.17592748]


In [44]:
print(np.random.randint(1,100, size = (2,5)))

[[12 39 54 70 55]
 [94 25 32 86  2]]


# Pandas

In [53]:
import pandas as pd

In [69]:
data = [10,20 ,30]

In [70]:
s = pd.Series(data, index=["a","b","c"])

In [71]:
s

a    10
b    20
c    30
dtype: int64

In [72]:
print(s["b"])

20


In [73]:
data = {
    "Name" : ['Ram', 'Shiv','honey'],
    'age': [12,34,45]
}

In [76]:
df = pd.DataFrame(data)
df

Name  age
0    Ram   12
1   Shiv   34
2  honey   45

In [77]:
print(df.info)

<bound method DataFrame.info of     Name  age
0    Ram   12
1   Shiv   34
2  honey   45>


In [80]:
print(df.head())

    Name  age
0    Ram   12
1   Shiv   34
2  honey   45


In [82]:
print(df.describe)

<bound method NDFrame.describe of     Name  age
0    Ram   12
1   Shiv   34
2  honey   45>


In [85]:
df["Grade"] = ["A","A+","C"]

In [95]:
df.tail(2)

Name  age Grade
1   Shiv   34    A+
2  honey   45     C

In [96]:
df.isnull()

Name    age  Grade
0  False  False  False
1  False  False  False
2  False  False  False

In [97]:
df["Marks"] = [90, None,100 ]

In [99]:
df.isnull()

Name    age  Grade  Marks
0  False  False  False  False
1  False  False  False   True
2  False  False  False  False

In [108]:
df = df.fillna(56, inplace = False)

In [109]:
df

Name  age Grade  Marks
0    Ram   12     A   90.0
1   Shiv   34    A+   56.0
2  honey   45     C  100.0

In [118]:
df = pd.read_csv("Sample DataSet/customers-100.csv")
df.tail(2)

Index      Customer Id First Name Last Name             Company  \
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer  Fitzgerald-Harrell   
99    100  2354a0E336A91A1   Clarence    Haynes  Le, Nash and Cross   

               City   Country        Phone 1                 Phone 2  \
98  Lake Elijahview     Aruba  (530)311-9786  001-869-452-0943x12424   
99        Judymouth  Honduras  (753)813-6941            783.639.1472   

                             Email Subscription Date  \
98  mccarthystephen@horn-green.biz        2021-08-11   
99          colleen91@faulkner.biz        2020-03-11   

                              Website  
98               http://watkins.info/  
99  http://www.hatfield-saunders.net/

In [123]:
df[df["Index"] > 8]

Index      Customer Id First Name  Last Name                     Company  \
8       9  C2dE4dEEc489ae0     Sheryl     Meyers              Browning-Simon   
9      10  8C2811a503C7c5a   Michelle  Gallagher                Beck-Hendrix   
10     11  216E205d6eBb815       Carl  Schroeder  Oconnell, Meza and Everett   
11     12  CEDec94deE6d69B      Jenna     Dodson   Hoffman, Reed and Mcclain   
12     13  e35426EbDEceaFF     Tracey       Mata              Graham-Francis   
..    ...              ...        ...        ...                         ...   
95     96  cb8E23e48d22Eae       Karl      Greer                   Carey LLC   
96     97  CeD220bdAaCfaDf       Lynn   Atkinson       Ware, Burns and Oneal   
97     98  28CDbC0dFe4b1Db       Fred     Guerra               Schmitt-Jones   
98     99  c23d1D9EE8DEB0A     Yvonne     Farmer          Fitzgerald-Harrell   
99    100  2354a0E336A91A1   Clarence     Haynes          Le, Nash and Cross   

                 City          Country               Phone 1  \
8        Robersonstad           Cyprus     854-138-4911x5772   
9          Elaineberg      Timor-Leste      739.218.2516x459   
10       Shannonville         Guernsey      637-854-0256x825   
11        East Andrea          Vietnam         (041)737-3846   
12  South Joannamouth             Togo      001-949-844-8787   
..                ...              ...                   ...   
95       East Richard           Guyana   (188)169-1674x58692   
96       New Bradview        Sri Lanka       +1-846-706-2218   
97         Ortegaland  Solomon Islands  +1-753-067-8419x7170   
98    Lake Elijahview            Aruba         (530)311-9786   
99          Judymouth         Honduras         (753)813-6941   

                   Phone 2                           Email Subscription Date  \
8      +1-448-910-2276x729         mariokhan@ryan-pope.org        2020-01-13   
9     001-054-401-0347x617               mdyer@escobar.net        2021-11-08   
10        114.336.0784x788              kirksalas@webb.com        2021-10-20   
11   +1-556-888-3485x42608              mark42@robbins.com        2020-11-29   
12           (855)713-8773                alex56@walls.org        2021-12-02   
..                     ...                             ...               ...   
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30   
96            605.413.3198               vkemp@ferrell.com        2021-07-10   
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18   
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11   
99            783.639.1472          colleen91@faulkner.biz        2020-03-11   

                              Website  
8            https://www.bullock.net/  
9                  https://arias.com/  
10        https://simmons-hurley.com/  
11            http://www.douglas.net/  
12               http://www.beck.com/  
..                                ...  
95            http://hayes-perez.com/  
96         https://novak-allison.com/  
97              https://www.ross.com/  
98               http://watkins.info/  
99  http://www.hatfield-saunders.net/  

[92 rows x 12 columns]

In [126]:
df.tail(10)

Index      Customer Id First Name Last Name                      Company  \
90     91  5ef6d3eefdD43bE       Nina    Chavez                Byrd-Campbell   
91     92  98b3aeDcC3B9FF3      Shane     Foley                   Rocha-Hart   
92     93  aAb6AFc7AfD0fF3     Collin     Ayers                Lamb-Peterson   
93     94  54B5B5Fe9F1B6C5     Sherry     Young      Lee, Lucero and Johnson   
94     95  BE91A0bdcA49Bbc    Darrell   Douglas  Newton, Petersen and Mathis   
95     96  cb8E23e48d22Eae       Karl     Greer                    Carey LLC   
96     97  CeD220bdAaCfaDf       Lynn  Atkinson        Ware, Burns and Oneal   
97     98  28CDbC0dFe4b1Db       Fred    Guerra                Schmitt-Jones   
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer           Fitzgerald-Harrell   
99    100  2354a0E336A91A1   Clarence    Haynes           Le, Nash and Cross   

                City          Country                Phone 1  \
90    Cassidychester           Bhutan           053-344-3205   
91  South Dannymouth          Hungary        +1-822-569-0302   
92      South Lonnie         Anguilla       404-645-5351x012   
93      Frankchester  Solomon Islands           158-687-1764   
94      Daisyborough             Mali  001-084-845-9524x1777   
95      East Richard           Guyana    (188)169-1674x58692   
96      New Bradview        Sri Lanka        +1-846-706-2218   
97        Ortegaland  Solomon Islands   +1-753-067-8419x7170   
98   Lake Elijahview            Aruba          (530)311-9786   
99         Judymouth         Honduras          (753)813-6941   

                   Phone 2                           Email Subscription Date  \
90     +1-330-920-5422x571            elliserica@frank.com        2020-03-26   
91  001-626-114-5844x55073              nsteele@sparks.com        2021-07-06   
92   001-257-582-8850x8516        dudleyemily@gonzales.biz        2021-06-29   
93       (438)375-6207x003     alan79@gates-mclaughlin.com        2021-04-04   
94        001-769-564-6303        grayjean@lowery-good.com        2022-02-17   
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30   
96            605.413.3198               vkemp@ferrell.com        2021-07-10   
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18   
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11   
99            783.639.1472          colleen91@faulkner.biz        2020-03-11   

                              Website  
90              https://www.pugh.com/  
91       https://www.holt-sparks.com/  
92               http://www.ruiz.com/  
93                https://travis.net/  
94                 https://banks.biz/  
95            http://hayes-perez.com/  
96         https://novak-allison.com/  
97              https://www.ross.com/  
98               http://watkins.info/  
99  http://www.hatfield-saunders.net/

In [128]:
df["Index"].count()

100

In [129]:
df["Country"]

0                          Chile
1                       Djibouti
2            Antigua and Barbuda
3             Dominican Republic
4     Slovakia (Slovak Republic)
                 ...            
95                        Guyana
96                     Sri Lanka
97               Solomon Islands
98                         Aruba
99                      Honduras
Name: Country, Length: 100, dtype: object